services:
  app:
    build:
      context: .
      target: dev
    command: "uv run mpt-ext run"
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/extension
    ports:
      - "8080:8080"
